pipeline:
  build:
    image: java:openjdk-8
    environment:
      - GRADLE_USER_HOME=~/.gradle
    commands:
      - ./gradlew test

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp
